name: ci

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: macOS-latest
    strategy:
      matrix:
        run-config:
          - { sdk: "iphoneos13.0" }
          - { sdk: "iphonesimulator13.0" }
    steps:
      - name: Checkout Project
        uses: actions/checkout@v2

      - name: Switch to Xcode 11
        run: sudo xcode-select -s /Applications/Xcode_11.app

      - name: Show Build Version
        run: xcodebuild -version

      - name: Show Build Settings
        run: xcodebuild -showBuildSettings
        
      - name: Show Build SDK
        run: xcodebuild -showsdks

      - name: Create Test Collateral
        run: |
          cat <<XCCONFIG > Development.xcconfig
          API_ENDPOINT = purposefully-invalid-url
          XCCONFIG

      - name: Run Build
        env:
          SDK: ${{ matrix.run-config['sdk'] }}
        run: xcodebuild -scheme CoLocate -sdk ${SDK} -allowProvisioningUpdates

  test:
    needs: build
    runs-on: macOS-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v2

      - name: Switch to Xcode 11
        run: sudo xcode-select -s /Applications/Xcode_11.app

      
      - name: Show Available Destinations
        run: xcodebuild -scheme CoLocate -showdestinations

      - name: Create Test Collateral
        run: |
          cat <<XCCONFIG > Development.xcconfig
          API_ENDPOINT = purposefully-invalid-url
          XCCONFIG
      
      - name: Run Test
        run: >
          xcodebuild
          -scheme CoLocate
          test
          -destination "platform=iOS Simulator,OS=13.0,name=iPhone 11"
          -showBuildTimingSummary
          -allowProvisioningUpdates

  deploy:
    needs: test
    runs-on: macOS-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Merge master into test-flight
        run: |
          git fetch origin test-flight
          git checkout test-flight
          git merge ${{ github.sha }}

      - name: Bump Version
        run: ./bin/bump-build-version

      - name: Commit Version Bump
        run: ./bin/commit-version-bump

        # - name: Push test-flight Branch
        #   env:
        #     GITHUB_TOKEN: ${{ secrets.github_token }}
        #   run: |
        #     git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
        #     git push origin test-flight
