name: ci

on:
  push:
    branches:
      - master
      - ci

jobs:
  build:
    runs-on:
      - self-hosted
      - macos
    strategy:
      matrix:
        run-config:
          - { sdk: "iphoneos13.4" }
          - { sdk: "iphonesimulator13.4" }
    steps:
      - name: Set initial git configuration
        run: git config --global user.email "sonarpivotaldevices@gmail.com" && git config --global user.name "Sonar CI"

      - name: Checkout Project
        uses: actions/checkout@v2

      - name: Switch to Xcode 11
        run: sudo xcode-select -s /Applications/Xcode_11.app

      - name: Show Build Version
        run: xcodebuild -version

      - name: Show Build Settings
        run: xcodebuild -showBuildSettings

      - name: Show Build SDK
        run: xcodebuild -showsdks

      - name: Setup Build Configuration
        run: ./bin/setup-build-config

      - name: Run Build
        env:
          SDK: ${{ matrix.run-config['sdk'] }}
        run: xcodebuild -scheme CoLocate -sdk ${SDK} CODE_SIGNING_ALLOWED=NO

  test:
    needs: build
    runs-on:
      - self-hosted
      - macos
    steps:
      - name: Checkout Project
        uses: actions/checkout@v2

      - name: Switch to Xcode 11
        run: sudo xcode-select -s /Applications/Xcode_11.app

      - name: Show Available Destinations
        run: xcodebuild -scheme CoLocateInternal -showdestinations

      - name: Setup Build Configuration
        run: ./bin/setup-build-config

      - name: Run Test
        run: >
          xcodebuild
          -scheme CoLocateInternal
          test
          -destination "platform=iOS Simulator,OS=13.4,name=iPhone 11"
          -showBuildTimingSummary
          -allowProvisioningUpdates

  trigger-deployment:
    needs: test
    runs-on:
      - self-hosted
      - macos
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Trigger deployment
        run: >
          curl
          --request POST
          --url https://api.github.com/repos/${{ github.repository }}/deployments
          --header 'authorization: Bearer ${{ secrets.deployment_token }}'
          --header 'content-type: application/json'
          --data '{
            "ref":"${{ github.sha }}",
            "required_contexts": [],
            "payload":"This issue was automatically created by the GitHub Action workflow **${{ github.workflow }}**. \n\n The commit hash was: _${{ github.sha }}_.",
            "environment":"staging"
          }'
