name: ci

on:
  push:
    branches-ignore:
      - ci

jobs:
  build:
    runs-on:
      - macos
    strategy:
      matrix:
        run-config:
          - { sdk: "iphoneos13.4" }
          - { sdk: "iphonesimulator13.4" }
    steps:
      - name: Checkout Project
        uses: actions/checkout@01aeccc # v2.1.0

      - name: Switch to Xcode 11
        run: sudo xcode-select -s /Applications/Xcode_11.app

      - name: Show Build Version
        run: xcodebuild -version

      - name: Show Build Settings
        run: xcodebuild -showBuildSettings

      - name: Show Build SDK
        run: xcodebuild -showsdks

      - name: Setup Build Configuration
        env:
          GOOGLE_SERVICE_INFO_PLIST_INTERNAL: ${{ secrets.google_service_info_plist_internal }}
        run: |
          cp Sonar/Environments/Sonar.xcconfig.sample .secret/Sonar.xcconfig
          echo $GOOGLE_SERVICE_INFO_PLIST_INTERNAL > .secret/GoogleService-Info.plist
          cat Sonar/Environments/environment.json | ./bin/make-environment > .secret/Environment.swift

      - name: Run Build
        env:
          SDK: ${{ matrix.run-config['sdk'] }}
        run: |
          xcodebuild -scheme Sonar -configuration release -sdk ${SDK} CODE_SIGNING_ALLOWED=NO
          xcodebuild -scheme Sonar -sdk ${SDK} build-for-testing CODE_SIGNING_ALLOWED=NO

  merge-to-internal:
    needs: build
    runs-on:
      - macos
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout Project
        uses: actions/checkout@01aeccc # v2.1.0
        with:
          fetch-depth: 0
          persist-credentials: false

      # Since this workflow needs to trigger the ci workflow,
      # we can't use the built-in GITHUB_TOKEN, so we need to
      # set a remote url that uses a personal access token.
      - name: Set origin
        env:
          GITHUB_TOKEN: ${{ secrets.deployment_token }}
        run: git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git

      - name: Merge and push to internal branch
        env:
          GIT_AUTHOR_NAME: GitHub Actions
          GIT_AUTHOR_EMAIL: github.actions@example.com
        run: |
          git fetch origin internal
          git checkout internal
          git merge master
          git push origin internal

