name: ci

on:
  push:
    branches-ignore:
      - ci

jobs:
  build:
    runs-on:
      - self-hosted
      - macos
    strategy:
      matrix:
        run-config:
          - { sdk: "iphoneos13.4" }
          - { sdk: "iphonesimulator13.4" }
    steps:
      - name: Checkout Project
        uses: actions/checkout@01aeccc # v2.1.0

      - name: Switch to Xcode 11
        run: sudo xcode-select -s /Applications/Xcode_11.app

      - name: Show Build Version
        run: xcodebuild -version

      - name: Show Build Settings
        run: xcodebuild -showBuildSettings

      - name: Show Build SDK
        run: xcodebuild -showsdks

      - name: Setup Build Configuration
        env:
          GOOGLE_SERVICE_INFO_PLIST_INTERNAL: ${{ secrets.google_service_info_plist_internal }}
        run: |
          cp Sonar/Environments/Sonar.xcconfig.sample .secret/Sonar.xcconfig
          echo $GOOGLE_SERVICE_INFO_PLIST_INTERNAL > .secret/GoogleService-Info.plist
          cat Sonar/Environments/environment.json | ./bin/make-environment > .secret/Environment.swift

      - name: Run Build
        env:
          SDK: ${{ matrix.run-config['sdk'] }}
        run: xcodebuild -scheme Sonar -configuration release -sdk ${SDK} CODE_SIGNING_ALLOWED=NO

  test:
    needs: build
    runs-on:
      - self-hosted
      - macos
    strategy:
      matrix:
        run-config:
          - { os: "13-4", name: "iPhone 11" }
          - { os: "12-4", name: "iPhone SE" }
    steps:
      - name: Checkout Project
        uses: actions/checkout@01aeccc # v2.1.0

      - name: Switch to Xcode 11
        run: sudo xcode-select -s /Applications/Xcode_11.app

      - name: Show Available Destinations
        run: xcodebuild -scheme Sonar -showdestinations

      - name: Setup Build Configuration
        env:
          GOOGLE_SERVICE_INFO_PLIST_INTERNAL: ${{ secrets.google_service_info_plist_internal }}
        run: |
          cp Sonar/Environments/Sonar.xcconfig.sample .secret/Sonar.xcconfig
          echo $GOOGLE_SERVICE_INFO_PLIST_INTERNAL > .secret/GoogleService-Info.plist
          cat Sonar/Environments/environment.json | ./bin/make-environment > .secret/Environment.swift

      - name: Delete leftover simulator devices
        run: |
          xcrun simctl shutdown all
          xcrun simctl erase all
          xcrun simctl delete all

      - name: Setup simulator test device
        id: devicesetup
        env:
          DEVICE_NAME: ${{ matrix.run-config['name'] }}
          DEVICE_OS: ${{ matrix.run-config['os'] }}
        run: |
          DEVICE_ID=$(xcrun simctl create test-device-${DEVICE_NAME/ /-}-$DEVICE_OS "$DEVICE_NAME" "com.apple.CoreSimulator.SimRuntime.iOS-$DEVICE_OS")
          echo "::set-output name=deviceid::$DEVICE_ID"

      - name: Boot simulator test device
        run: xcrun simctl bootstatus ${{ steps.devicesetup.outputs.deviceid }} -b

      - name: Set up pact
        run: bin/pact/setup

      - run: |
          [[ -d TestResults.xcresult ]] && rm -rf TestResults.xcresult || true
          [[ -d PactTestResults.xcresult ]] && rm -rf PactTestResults.xcresult || true

      - name: Run Tests
        run: >
          xcodebuild
          -scheme Sonar
          test
          -destination "id=${{ steps.devicesetup.outputs.deviceid }}"
          -showBuildTimingSummary
          -allowProvisioningUpdates
          -resultBundlePath TestResults.xcresult

      - name: Run Pact Tests
        run: >
          xcodebuild
          -scheme 'Sonar Pact Tests'
          -target SonarPactTests
          test
          -destination "id=${{ steps.devicesetup.outputs.deviceid }}"
          -showBuildTimingSummary
          -allowProvisioningUpdates
          -resultBundlePath PactTestResults.xcresult

      - name: Shutdown and erase simulator test device
        if: always()
        run: |
          xcrun simctl shutdown ${{ steps.devicesetup.outputs.deviceid }}
          xcrun simctl erase ${{ steps.devicesetup.outputs.deviceid }}
          xcrun simctl delete ${{ steps.devicesetup.outputs.deviceid }}

      - name: Upload Pacts
        uses: actions/upload-artifact@e7eefc4 # v2
        with:
          name: pacts-${{ github.sha }}
          path: Pacts

      - name: Upload Pact Test Results
        if: always()
        uses: actions/upload-artifact@e7eefc4 # v2
        with:
          name: PactTestResults.xcresult
          path: PactTestResults.xcresult

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@e7eefc4 # v2
        with:
          name: TestResults.xcresult
          path: TestResults.xcresult

  upload-pacts-to-broker:
    needs: test
    runs-on:
      - macos
      - self-hosted
    steps:
      - name: Download Pacts
        uses: actions/download-artifact@v2
        with:
          name: pacts-${{ github.sha }}
          path: Pacts
      - name: Upload Pacts to Pact Broker
        continue-on-error: true
        run: >
          pact-broker publish Pacts --consumer-app-version=$(echo ${{ github.sha }} | cut -c-7)
        env:
          PACT_BROKER_BASE_URL: https://sonar-pact-broker-app.apps.nonprod.aws.cp.data.england.nhs.uk


  merge-to-internal:
    needs: test
    runs-on:
      - self-hosted
      - macos
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout Project
        uses: actions/checkout@01aeccc # v2.1.0
        with:
          fetch-depth: 0
          persist-credentials: false

      # Since this workflow needs to trigger the ci workflow,
      # we can't use the built-in GITHUB_TOKEN, so we need to
      # set a remote url that uses a personal access token.
      - name: Set origin
        env:
          GITHUB_TOKEN: ${{ secrets.deployment_token }}
        run: git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git

      - name: Merge and push to internal branch
        env:
          GIT_AUTHOR_NAME: GitHub Actions
          GIT_AUTHOR_EMAIL: github.actions@example.com
        run: |
          git fetch origin internal
          git checkout internal
          git merge master
          git push origin internal

  notify:
    needs: [build, test, merge-to-internal]
    runs-on:
      - self-hosted
      - macos
    if: always()
    steps:
      - name: Notify Slack on Failure
        if: github.ref == 'refs/heads/master' && contains(needs.*.result, 'failure')
        env:
          SLACK_BOT_TOKEN: ${{ secrets.slack_bot_token }}
        uses: voxmedia/github-action-slack-notify-build@5125947 # v1.1.1
        with:
          channel_id: G011ZPSAD4J
          status: FAILED
          color: danger

