name: generate-release-note

on:
  repository_dispatch:
    types: [generate-release-note]

jobs:
  generate-release-note:
    runs-on:
      - linux
      - aws
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # checkout full repo with all tags

      - name: Checkout ci tools
        id: checkout-ci-tools
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.DEPLOYMENT_TOKEN }}
          repository: nhsx/sonar-ci-tools
          path: ci-tools
          ref: v0.2.0

      - name: Generate release notes
        id: generate_release_notes
        uses: ./ci-tools/.github/actions/generate-release-notes
        with:
          tracker_token: ${{ secrets.tracker_api_token }}
          revision_range: ${{ github.event.client_payload.revision_range }}

      - name: Print release notes
        run: echo "${{ steps.generate_release_notes.outputs.release_notes }}"
