name: test-flight

on:
  push:
    branches:
      - test-flight

jobs:
  release:
    runs-on: macOS-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v2

      - name: Switch to Xcode 11
        run: sudo xcode-select -s /Applications/Xcode_11.app

      - name: Install Fastlane
        run: gem install fastlane

      - name: Setup Development Config
        run: cp Development.xcconfig.sample Development.xcconfig

      - name: Setup Release Config
        env:
          API_ENDPOINT: ${{ secrets.api_endpoint }}
        run: |
          echo <<XCCONFIG > Release.xcconfig
          API_ENDPOINT = $API_ENDPOINT
          XCCONFIG

      - name: Setup Fastlane Match
        env:
          DISTRIBUTION_CER: ${{ secrets.distribution_cer }}
          DISTRIBUTION_P12: ${{ secrets.distribution_p12 }}
          PROVISIONING_PROFILE: ${{ secrets.provisioning_profile }}
        run: ./bin/setup-match

      - name: Upload to Test Flight
        env:
          APPLE_USERNAME: ${{ secrets.apple_username }}
          FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{ secrets.apple_password }}
          MATCH_PASSWORD: ${{ secrets.match_password }}
        run: fastlane beta
