name: trigger-upload

on:
  # schedule:
  #   - cron: 0 * * * *
  push:
    branches:
      - master

jobs:
  trigger-deployment:
    needs: test
    runs-on:
      - self-hosted
      - macos
    steps:
      - name: Checkout Project
        uses: actions/checkout@v2
        with:
          ref: test-flight
          fetch-depth: 0

      - name: Check if we have commits to upload
        id: check-ready-for-upload
        run: |
          git fetch ready-for-upload
          git branch --contains tags/ready-for-upload | grep test-flight
          echo "::set-output name=ready-for-upload::$?"

      - name: Trigger deployment
        if: steps.check-ready-for-upload.outputs.ready-for-upload == '1'
        run: >
          curl
          --request POST
          --url https://api.github.com/repos/${{ github.repository }}/deployments
          --header 'authorization: Bearer ${{ secrets.deployment_token }}'
          --header 'content-type: application/json'
          --data '{
            "ref":"${{ github.sha }}",
            "required_contexts": [],
            "payload":"This issue was automatically created by the GitHub Action workflow **${{ github.workflow }}**. \n\n The commit hash was: _${{ github.sha }}_.",
            "environment":"staging"
          }'
