name: trigger-upload

on:
  schedule:
    - cron: '0 */2 * * *'
  # push:
  #   branches:
  #     - ci

jobs:
  trigger-upload:
    runs-on:
      - self-hosted
      - macos
    steps:
      - name: Checkout Project
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Check if we have commits to upload
        id: check-upload-tag
        run: |
          git fetch origin test-flight
          git checkout test-flight
          git fetch --tags
          git branch --contains tags/upload-to-test-flight | grep test-flight || echo "::set-output name=upload::true"

      - name: Trigger deployment
        if: steps.check-upload-tag.outputs.upload == 'true'
        env:
          GITHUB_RESPOSITORY: ${{ github.repository }}
          GITHUB_ACCESS_TOKEN: ${{ secrets.deployment_token }}
          GITHUB_SHA: ${{ github.sha }}
          DEPLOYMENT_PAYLOAD: 'This issue was automatically created by the GitHub Action workflow **${{ github.workflow }}**.\n\nThe commit hash was: _${{ github.sha }}_.'
        run: ./bin/create-deployment internal
        # continue-on-error: true

      - name: Notify Slack on Failure
        if: failure()
        env:
          SLACK_BOT_TOKEN: ${{ secrets.slack_bot_token }}
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          channel_id: G011ZPSAD4J
          status: FAILED
          color: danger
