name: unit-tests

on:
  push:
    branches:
      - master
      - ci

jobs:
  build:
    runs-on:
      - self-hosted
      - macos
    strategy:
      matrix:
        run-config:
          - { sdk: "iphoneos13.4" }
          - { sdk: "iphonesimulator13.4" }
    steps:
      - name: Set initial git configuration
        run: git config --global user.email "sonarpivotaldevices@gmail.com" && git config --global user.name "Sonar CI"

      - name: Checkout Project
        uses: actions/checkout@v2

      - name: Switch to Xcode 11
        run: sudo xcode-select -s /Applications/Xcode_11.app

      - name: Show Build Version
        run: xcodebuild -version

      - name: Show Build Settings
        run: xcodebuild -showBuildSettings

      - name: Show Build SDK
        run: xcodebuild -showsdks

      - name: Setup Build Configuration
        run: cp CoLocate.xcconfig.sample CoLocate.xcconfig

      - name: Run Build
        env:
          SDK: ${{ matrix.run-config['sdk'] }}
        run: xcodebuild -scheme CoLocate -sdk ${SDK} CODE_SIGNING_ALLOWED=NO

      - name: Notify Slack on Failure
        if: github.ref == 'refs/heads/master' && failure()
        env:
          SLACK_BOT_TOKEN: ${{ secrets.slack_bot_token }}
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          channel_id: G011ZPSAD4J
          status: FAILED
          color: danger

  test:
    needs: build
    runs-on:
      - self-hosted
      - macos
    steps:
      - name: Checkout Project
        uses: actions/checkout@v2

      - name: Switch to Xcode 11
        run: sudo xcode-select -s /Applications/Xcode_11.app

      - name: Show Available Destinations
        run: xcodebuild -scheme CoLocate -showdestinations

      - name: Setup Build Configuration
        run: cp CoLocate.xcconfig.sample CoLocate.xcconfig

      - run: |
          killall "Simulator" || true
          xcrun simctl erase all

      - name: Run Test
        run: >
          xcodebuild
          -scheme CoLocate
          test
          -destination "platform=iOS Simulator,OS=13.4,name=iPhone 11"
          -showBuildTimingSummary
          -allowProvisioningUpdates

      - name: Notify Slack on Failure
        if: github.ref == 'refs/heads/master' && failure()
        env:
          SLACK_BOT_TOKEN: ${{ secrets.slack_bot_token }}
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          channel_id: G011ZPSAD4J
          status: FAILED
          color: danger

  update-upload-tag:
    needs: test
    runs-on:
      - self-hosted
      - macos
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout Project
        uses: actions/checkout@v2

      - name: Set upload tag
        run: |
          git push origin --delete upload-to-test-flight || true
          git tag --force upload-to-test-flight
          git push origin upload-to-test-flight
